version: '3'
services:
  db:
    image: 'postgres:13-alpine'
  redis:
    image: 'redis:6-alpine'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/md715/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=${PG_USERNAME}
      - PGPASSWORD=${PG_PASSWORD}
      - PGDATABASE=md715_development
      - PGHOST=postgres
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/md715/node_modules
      - ./client:/opt/md715
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/md715/node_modules
      - ./worker:/opt/md715
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  proxy:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 4000:80
    depends_on:
      - api
      - client